name: chatting
description: Chat-related functions
version: 0.1.0
homepage:

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.0.0
  equatable: ^2.0.3
  json_serializable: ^6.1.1
  json_annotation: ^4.4.0
  firebase_core: ^1.12.0
  cloud_firestore: ^3.1.8
  intl: ^0.17.0
  flutter_slidable: ^1.2.0
  collection: ^1.15.0
  chat_bubbles: ^1.2.0
  adaptive_dialog: ^1.3.0
  shared_preferences: ^2.0.13
  uuid: ^3.0.5
  flutter_svg: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  assets:
    - assets/images/
  uses-material-design: true
  module:
    androidX: true
    androidPackage: me.squeezymo.components
    iosBundleIdentifier: me.squeezymo.components
